<?php

namespace AppBundle\Repository;

/**
 * AccountDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
