<?php

namespace AppBundle\Repository;

/**
 * ExporterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExporterRepository extends \Doctrine\ORM\EntityRepository
{
}
