<?php

namespace AppBundle\Repository;

/**
 * IpCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IpCountryRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCountry($ip)
    {
    	$long = ip2long($ip);
        $country = $this->getEntityManager()
            ->createQuery(
                'SELECT ip_country.countryCode FROM AppBundle:IpCountry ip_country WHERE '.$long.' > ip_country.startIp AND '.$long.' < ip_country.endIp'
            )
            ->getOneOrNullResult();

            return ($country)? $country['countryCode']:false;
    }
}
