<?php

namespace AppBundle\Repository;

/**
 * TextToSpeechRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextToSpeechRepository extends \Doctrine\ORM\EntityRepository
{
}
