<?php

namespace AppBundle\Repository;

/**
 * TexturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TexturesRepository extends \Doctrine\ORM\EntityRepository
{
}
