<?php

namespace AppBundle\Repository;

/**
 * TimebaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimebaseRepository extends \Doctrine\ORM\EntityRepository
{
}
