<?php

namespace AppBundle\Repository;

/**
 * TrialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrialRepository extends \Doctrine\ORM\EntityRepository
{
}
